spring: 
  application:
    name: smallrain-wechat
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.12.204.7:3306/template?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: template
    password: 123456
    
server: 
  port: 8088
  tomcat:
    uri-encoding: UTF-8
    max-threads: 100
    accept-count: 500
    max-connections: 1024
  timeout: 30000
  session:
    timeout: 30000
    
    
wx:
 miniapp:
   configs:
       - appid: #微信小程序的appid
         secret: #微信小程序的Secret
         token: #微信小程序消息服务器配置的token
         aesKey: #微信小程序消息服务器配置的EncodingAESKey
         msgDataFormat: JSON