#服务配置
server: 
  port: 80
  tomcat:
    uri-encoding: UTF-8
    max-threads: 128
    accept-count: 500
    max-connections: 4096
  timeout: 60000
  session:
    timeout: 60000

spring: 
  application:
    name: smallrain-wechat
  #页面模板配置
  freemarker:
    # 设置模板后缀名
    suffix: .html
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false
    template-encoding: UTF-8
    # 设置ftl文件路径
    template-loader-path:
      - classpath:/templates
  mvc:
    static-path-pattern: /static/**
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://${DB_HOST:121.199.42.156}:${DB_PORT:3306}/${DB_NAME:smallrain_template}?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
      username: root
      password: ${DB_PASSWORD:root}
      initialSize: 8
      minIdle: 4
      maxActive: 32
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      #filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
    
wx:
 miniapp:
   configs:
       - appid: #微信小程序的appid
         secret: #微信小程序的Secret
         token: #微信小程序消息服务器配置的token
         aesKey: #微信小程序消息服务器配置的EncodingAESKey
         msgDataFormat: JSON